<?php
/**
 * @file
 * Code for the hot-bs-carousel feature.
 */

include_once 'hot_bs_carousel.features.inc';
/**
 * @file
 * hot-bs-carousel Module file
 */


/**
 * Implements hook_theme().
 */
function hot_bs_carousel_theme() {
  $theme = array(
    'carousel' => array(
      'variables' => array(
        'slides' => NULL,
        'controls' => NULL,
        'indicators' =>  NULL
      ),
      'template' => 'templates/carousel',
      'type' => 'module'
    ),
    'carousel_slide' => array(
      'variables' => array(
        'image' => NULL,
        'title' => NULL,
        'caption' => NULL
      ),
      'template' => 'templates/carousel-slide',
      'type' => 'module',
    ),
    'carousel_controls' => array(
      'template' => 'templates/carousel-controls',
      'type' => 'module',
    ),
    'carousel_indicators' => array(
      'template' => 'templates/carousel-indicators',
      'variables' => array('items' => NULL),
      'type' => 'module',
    ),
    'fieldable_panels_pane__hot_bs_carousel' => array(
      'template' => 'templates/fieldable-panels-pane--hot-bs-carousel',
      'preprocess functions' => array('')
    )
  );
  return $theme;
}



/**
 * Implements hook_entity_info_alter().
 *
 * Defines the field-able pane for bootstrap carousels
 * @link( Bootstrap JS, http://getbootstrap.com/javascript/)
 */
function hot_bs_carousel_entity_info_alter(&$entity_info) {

  // Fieldable panel pane bundle to support Bootstrap carousels:
  $entity_info['fieldable_panels_pane']['bundles']['hot_bs_carousel'] = array(
    'label' => t('Carousel'),
    'pane category' => t('HotApps!'),
    'pane top level' => FALSE,
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-bs-carousel',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}



/**
* Implements hook_preprocess_panels_pane().
*/
function hot_bs_carousel_preprocess_fieldable_panels_pane(&$vars){
  $carousel = theme('carousel', array());

  $vars['fields'] = $carousel;
}
