<?php
/**
 * @file
 * Code for the hot-bs-carousel feature.
 */

include_once 'hot_bs_carousel.features.inc';

/**
 * Implements hook_theme().
 */
function hot_bs_carousel_theme() {
  $theme = array(
    'carousel' => array(
      'variables' => array(
        'slides' => NULL,
      ),
      'template' => 'templates/carousel',
      'type' => 'module',
    ),
    'carousel_slide' => array(
      'variables' => array(
        'image' => NULL,
        'title' => NULL,
        'caption' => NULL,
        'active' => FALSE,
      ),
      'template' => 'templates/carousel-slide',
      'type' => 'module',
    ),
    'carousel_indicators' => array(
      'template' => 'templates/carousel-indicators',
      'variables' => array(
        'items' => NULL,
        'target' => NULL,
      ),
      'type' => 'module',
    ),
    'carousel_controls' => array(
      'template'  => 'templates/carousel-controls',
      'variables' => array('target' => NULL),
    ),
    'fieldable_panels_pane__hot_bs_carousel' => array(
      'template' => 'templates/fieldable-panels-pane--hot-bs-carousel',
    ),
  );
  return $theme;
}
/**
 * Implements templates_process_carousel().
 */
function template_process_carousel(&$variables) {
  $variables['id_string'] = 'hotBsCarousel' . $variables['id'];
}

/**
 * Implements hook_entity_info_alter().
 *
 * Defines the field-able pane for bootstrap carousels
 * @link( Bootstrap JS, http://getbootstrap.com/javascript/)
 */
function hot_bs_carousel_entity_info_alter(&$entity_info) {

  // Fieldable panel pane bundle to support Bootstrap carousels:
  $entity_info['fieldable_panels_pane']['bundles']['hot_bs_carousel'] = array(
    'label' => t('Carousel'),
    'pane category' => t('HotApps!'),
    'pane top level' => FALSE,
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot-bs-carousel',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_panels_pane().
 */
function hot_bs_carousel_preprocess_fieldable_panels_pane(&$vars) {
  if(isset($vars['elements']['#bundle']) && $vars['elements']['#bundle'] === 'hot_bs_carousel') {
    $vars['fields'] = _hot_bs_carousel_handle_view($vars);
  }
}

/**
 * Heloer function to theme out the carousel contents.
 */
function _hot_bs_carousel_handle_view(array $vars){
  $carousel = '';
  $slides = array();
  $field_hot_bs_carousel_slide = $vars['elements']['field_hot_bs_carousel_slide'];
  $count = 0;
  foreach ($field_hot_bs_carousel_slide as $key => $item) {
    if (is_numeric($key)) {
      foreach ($item['entity']['field_collection_item'] as $k => $i) {
        $active = $count < 1 ? TRUE : FALSE;
        $slides[$key] = array(
          '#theme' => 'carousel_slide',
          '#title' => render($i['field_hot_bs_carousel_s_title'][0]),
          '#caption' => render($i['field_hot_bs_carousel_slide_capt'][0]),
          '#image' => render($i['field_hot_bs_carousel_s_img'][0]),
          '#active' => $active,
        );
        $count++;
      }
    }
  }

  drupal_add_js(drupal_get_path('module','hot_bs_carousel') . '/hot_bs_carousel.min.js');
  $carousel = theme('carousel', array('slides' => $slides));
  
  return $carousel;
}
